import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nowAlt = localFont({
    variable: "--font-now-alt",
    src: [
        {
            path: "../../public/fonts/NowAlt-Regular.otf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/NowAlt-Medium.otf",
            weight: "500",
            style: "normal",
        },
    ],
});

const healTheWebA = localFont({
    variable: "--font-heal-the-web-a",
    src: [
        {
            path: "../../public/fonts/HealTheWebA-Regular.otf",
            weight: "400",
            style: "normal",
        },
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${healTheWebA.variable} ${nowAlt.variable}  antialiased`}
        >
            <body>{children}</body>
        </html>
    );
}
