name: Deploy subfolder and README to gh-pages

on:
    workflow_dispatch:
        inputs:
            subfolder:
                description: "Subfolder to deploy (relative to repo root)"
                required: true
    push:
        paths:
            - "p5-springsbased-physics-kicking/**"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install root dependencies
              run: npm install

            - name: Determine subfolder to build/deploy
              id: subfolder
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    echo "subfolder=${{ github.event.inputs.subfolder }}" >> $GITHUB_OUTPUT
                  else
                    # Only relevant subfolders will trigger this workflow due to the 'paths' filter above.
                    # Find the first-level directory of the first changed file in the push.
                    CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | head -n1)
                    TOPLEVEL=$(echo "$CHANGED" | cut -d/ -f1)
                    echo "subfolder=$TOPLEVEL" >> $GITHUB_OUTPUT
                  fi

            - name: Install subproject dependencies
              run: |
                  cd "${{ steps.subfolder.outputs.subfolder }}"
                  npm install
                  cd ..

            - name: Build only the subfolder
              run: node scripts/build.js "${{ steps.subfolder.outputs.subfolder }}"

            - name: Fetch gh-pages
              run: |
                  git fetch origin gh-pages:gh-pages || true

            - name: Prepare deployment folder
              run: |
                  mkdir gh-pages-content
                  if git rev-parse --verify gh-pages; then
                    git --work-tree=gh-pages-content checkout gh-pages -- . || true
                  fi

            - name: Copy subfolder for deployment
              run: |
                  SUBFOLDER="${{ steps.subfolder.outputs.subfolder }}"
                  rm -rf "gh-pages-content/$SUBFOLDER"
                  cp -r "$SUBFOLDER" gh-pages-content/

            - name: Copy README as index.md
              run: |
                  cp README.md gh-pages-content/index.md

            - name: Publish to gh-pages
              run: |
                  cd gh-pages-content
                  git init
                  git config user.name "${{ github.actor }}"
                  git config user.email "${{ github.actor }}@users.noreply.github.com"
                  git add .
                  git commit -m "Update subfolder and root README"
                  git branch -M gh-pages
                  git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
                  git push --force origin gh-pages
